### ISSUE TITLE
The provider code doesn't compile

### ISSUE THREAD

**Issue by robertofpaf** [jelmersnoeck/terraform-provider-aiven#11]
Hello,

I've created a fork of the project to add support for Kafka topics there, but I am not able to compile it. What I did is:

1. Cloned the repository locally
2. Ran glide install
3. Ran make

The end result is:

```
robertof@robfas-lin:~/go/src/terraform-provider-aiven (master)$ make
go build -o terraform-provider-aiven .
# terraform-provider-aiven
./provider.go:39:11: undefined: aiven.NewMFAUserClient
./resource_service_user.go:79:27: user.AccessCert undefined (type *aiven.ServiceUser has no field or method AccessCert)
./resource_service_user.go:80:26: user.AccessKey undefined (type *aiven.ServiceUser has no field or method AccessKey)
./resource_service_user.go:102:29: user.AccessCert undefined (type *aiven.ServiceUser has no field or method AccessCert)
./resource_service_user.go:103:28: user.AccessKey undefined (type *aiven.ServiceUser has no field or method AccessKey)
Makefile:2: recipe for target 'plugin' failed
make: *** [plugin] Error 2
```

I believe the issue is that https://github.com/jelmersnoeck/terraform-provider-aiven/pull/5 and https://github.com/jelmersnoeck/terraform-provider-aiven/pull/9 require changes to the aiven client but those haven't been merged back to the repo referenced in the glide file. So @jelmersnoeck @FranOis can that be done?

**Comment by FranOis** [comment]
@robertofpaf Hi, I haven't been working on this in on long while. You are correct that it would require a new version if you don't want to work off of master. My setup was to have both in my go path and develop from my local branches.

I'm not sure what the process of doing a release would be for the aiven client. @jelmersnoeck Would be the one to contact.

**Comment by robertofpaf** [comment]
@FranOis I'm working out of master, but the problem is that the changes required in the aiven client (MFA support and auth tokens for users) are in the master branch of your fork (https://github.com/motivateco/aiven) and not in the master branch of the original project (https://github.com/jelmersnoeck/aiven). And your fork is 11 commits behind, so I would believe the best thing to do would be to try and merge your fork back...

**Comment by FranOis** [comment]
Our master is out of date, but the NewMFAClient still exists in the original project as far as I can tell: https://github.com/jelmersnoeck/aiven/blob/master/client.go#L27

**Comment by jelmersnoeck** [comment]
Hey @robertofpaf. Thanks for highlighting this.

This is actually associated with the [ServiceUser](https://github.com/jelmersnoeck/aiven/blob/master/service_user.go). It seems that https://github.com/jelmersnoeck/terraform-provider-aiven/issues/8 added a change here for the Aiven client, but this wasn't patched. 

@FranOis could you do the appropriate patch for the Aiven Client as well?

I will look at setting up CI for this project soon.

**Comment by robertofpaf** [comment]
@FranOis What is the situation here?

@jelmersnoeck Should I just send a PR that undoes https://github.com/jelmersnoeck/terraform-provider-aiven/pull/9 to get the code compiling?

**Comment by robertofpaf** [comment]
Ok eventually submitted https://github.com/jelmersnoeck/aiven/pull/10, it brings back the 2 field that got deleted (I guess by mistake) in https://github.com/jelmersnoeck/aiven/pull/4 and the provider now compiles.

**Comment by FranOis** [comment]
@robertofpaf what's the status? can we close? seems like everything is compiling.

**Comment by robertofpaf** [comment]
Ah, I thought this was closed when the PR was merged already.
